version: "3.9"

services:
  showroom-database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "showroom_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5400:5432"
  factory-database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "factory_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5401:5432"
